POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjNlOGRhZTMwZjRhZTFhOGJmZjhkNiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2NjMzMDIyNjcsImV4cCI6MTY2NTg5NDI2N30.cYlz0BqXFSVYhdxWOK3kEWM8_78elrSZvaBm890U_oM

{
    "title": "Testing Put v8",
    "content": "Test",
    "important": true
}