DELETE http://localhost:3001/api/notes/633b00098cf76fd858bc631d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjNlOGRhZTMwZjRhZTFhOGJmZjhkNiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2NjMzMDIyNjcsImV4cCI6MTY2NTg5NDI2N30.cYlz0BqXFSVYhdxWOK3kEWM8_78elrSZvaBm890U_oM